"use server";

import { GoogleGenerativeAI } from "@google/generative-ai";
import { z } from "zod";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const model = genAI.getGenerativeModel({
  model: "gemini-2.5-flash",
});

// Define exactly what Gemini is allowed to return
const CoverLetterSchema = z.object({
  opening: z.string(),
  relevantExperience: z.string(),
  motivation: z.string(),
  closing: z.string(),
});

export async function generateCoverLetter(data) {
  /*
    Expected data:

    {
      jobTitle: "Software Engineer",
      companyName: "Tech Solutions Pvt. Ltd.",
      jobDescription: "We are looking for...",
      industry: "Information Technology",
      experience: "2 years",
      skills: ["Python", "Machine Learning", "SQL"],
      bio: "A passionate developer with experience building AI-driven apps."
    }
  */

  // Basic validation before sending anything to Gemini
  if (!data) {
    throw new Error("Candidate data is required");
  }

  if (!data.jobDescription) {
    throw new Error("Job description is required");
  }

  const prompt = `
You are a professional HR writing assistant.

Your task is to create a professional cover letter using ONLY
the factual information provided below.

========================
CANDIDATE INFORMATION
========================

Industry:
${data.industry || "Not provided"}

Experience:
${data.experience || "Not provided"}

Skills:
${data.skills?.join(", ") || "Not provided"}

Background:
${data.bio || "Not provided"}

========================
JOB INFORMATION
========================

Position:
${data.jobTitle || "Not provided"}

Company:
${data.companyName || "Not provided"}

Job Description:
${data.jobDescription}

========================
STRICT FACT RULES
========================

1. Use ONLY information explicitly provided above.

2. NEVER invent:
   - employers
   - projects
   - achievements
   - certifications
   - responsibilities
   - technologies
   - degrees
   - awards
   - metrics
   - years of experience

3. Do not assume that a listed skill means professional
   experience with that skill.

4. Do not create fake numerical achievements such as:
   "increased performance by 30%"
   unless that number was explicitly provided.

5. If information is missing, simply avoid mentioning it.

6. Do not claim the candidate has experience with something
   unless it is explicitly present in the candidate information.

7. Mention the company name only if it was provided.

8. Connect the candidate's provided skills/background to
   requirements in the job description without inventing
   additional experience.

9. Keep the letter under 400 words.

10. Return ONLY valid JSON.
Do not return markdown.
Do not return explanations.

========================
REQUIRED JSON FORMAT
========================

{
  "opening": "...",
  "relevantExperience": "...",
  "motivation": "...",
  "closing": "..."
}
`;

  try {
    const result = await model.generateContent(prompt);

    const rawOutput = result.response.text().trim();

    if (!rawOutput) {
      throw new Error("No content generated by model");
    }

    // Remove ```json ... ``` if Gemini happens to add it
    const cleanedOutput = rawOutput
      .replace(/^```json\s*/i, "")
      .replace(/^```\s*/i, "")
      .replace(/\s*```$/i, "")
      .trim();

    // Convert Gemini's JSON string into JavaScript object
    const parsedOutput = JSON.parse(cleanedOutput);

    // Validate Gemini's response
    const validatedOutput = CoverLetterSchema.parse(parsedOutput);

    // Build the final letter ourselves
    const coverLetter = `
Dear Hiring Manager,

${validatedOutput.opening}

${validatedOutput.relevantExperience}

${validatedOutput.motivation}

${validatedOutput.closing}

Sincerely,
Candidate
`.trim();

    return coverLetter;

  } catch (error) {
    console.error("Error generating cover letter:", error);

    throw new Error("Failed to generate cover letter");
  }
}